/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata */
        get: operations["metadata_api_v1_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend */
        post: operations["recommend_api_v1_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Article */
        Article: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Summary */
            summary: string;
            /** Category */
            category: string;
            /** Decision Label */
            decision_label: string;
        };
        /** Catalog */
        Catalog: {
            /** Source */
            source: string;
            /** Fetched At */
            fetched_at: string;
            /** Articles */
            articles: components["schemas"]["Article"][];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** Metadata */
        Metadata: {
            catalog: components["schemas"]["Catalog"];
            /** Providers */
            providers: components["schemas"]["ProviderInfo"][];
        };
        /** OptionResult */
        OptionResult: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url: string | null;
            /** Summary */
            summary: string;
            /** Category */
            category: string;
            /** Probability */
            probability: number;
            /** Is None */
            is_none: boolean;
        };
        /** ProviderInfo */
        ProviderInfo: {
            /**
             * Id
             * @enum {string}
             */
            id: "laya" | "jev";
            /** Name */
            name: string;
            /** Model */
            model: string;
            /** Available */
            available: boolean;
            /** Loaded */
            loaded: boolean;
            /** Reason */
            reason?: string | null;
            /** Device */
            device?: string | null;
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            /** Question */
            question: string;
            /**
             * Provider
             * @default laya
             * @enum {string}
             */
            provider: "laya" | "jev";
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Request Id */
            request_id: string;
            /** Question */
            question: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "laya" | "jev";
            /** Model */
            model: string;
            /** Model Revision */
            model_revision: string | null;
            /** Device */
            device: string;
            /** Recommended Id */
            recommended_id: string;
            /** Options */
            options: components["schemas"]["OptionResult"][];
            timing: components["schemas"]["Timing"];
            /** Input Tokens */
            input_tokens: number | null;
            /** Catalog Version */
            catalog_version: string;
            /** Prompt Version */
            prompt_version: string;
            /**
             * Probability Kind
             * @default categorical_choice
             * @constant
             */
            probability_kind: "categorical_choice";
        };
        /** Timing */
        Timing: {
            /** Model Load Ms */
            model_load_ms: number;
            /** Inference Ms */
            inference_ms: number;
            /** Server Total Ms */
            server_total_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metadata_api_v1_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metadata"];
                };
            };
        };
    };
    recommend_api_v1_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
